### PR TITLE
Fix of hash_payload for Ledger signData calls.

### PR DESCRIPTION
**Pull request by MarcelKlammer**

### CODE REVIEW

**Comment by MarcelKlammer** [comment]
It would be nice to get this merged, so dapps can update their libs and code to be able to handle Ledger's hashed payloads.

**Comment by MarcelKlammer** [comment]
Tagging @lisicky as you work on CSL, you maybe have contacts to the right persons.

**Comment by lisicky** [comment]
Hi @MarcelKlammer ! Could you provide a link to get more context ?

**Comment by MarcelKlammer** [comment]
There is CIP8:

https://github.com/cardano-foundation/CIPs/blob/master/CIP-0008/README.md

And Ledger's implementation, which hashes payloads with length > 99.

This small PR fixes the message signing lib, to properly set hashed: true, if the payload is indeed hashed.

**Review by SebastienGllmt — APPROVED** [review]

**Review by zuzunker — APPROVED** [review]
Thank you, @MarcelKlammer !

**Comment by lisicky** [comment]
Just FYI
the new version is on NPM [1.1.0](https://www.npmjs.com/package/@emurgo/cardano-message-signing-browser/v/1.1.0)

**Pull request merged**
